apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
  namespace: venkatesh-ns
  labels:
    app: bms
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bookmyshow-container
        image: dudduvenkatesh/bookmyshow:latest
        ports:
        - containerPort: 3000  
 # Replace with the port your app runs on
